############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/#about"
weight = 2

[[main]]
name = "Skills"
url = "/#skills"
weight = 3

[[main]]
name = "Projects"
url = "/#projects"
weight = 5

# footer menu
[[footer]]
name = "About"
url = "/#about"
weight = 1

