apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
resources:
  - ../../base
  - rollout.yaml
images:
  - name: docker.io/champoi/champcaptures
    newTag: f2471bb664c45d417f506008ac9d285700359997
