apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
resources:
  - ../../base
  - rollout.yaml
patchesStrategicMerge:
  - patch-gremlin-serviceid.yaml
  - patch-gremlin-rollout-metadata.yaml
  - patch-gremlin-service-annotations.yaml
images:
  - name: docker.io/champoi/champcaptures
    newTag: e3f7b917fc968803c57b2959795864fa3ecddae6
