apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
resources:
  - ../../base
  - rollout.yaml
images:
  - name: docker.io/champoi/champcaptures
    newTag: 2dd691f34dfc149cb2ec326009f9f3efc448bf5d
