apiVersion: apps/v1
kind: Deployment
metadata:
  name: champcaptures
  labels:
    app: champcaptures
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: champcaptures
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: champcaptures
    spec:
      imagePullSecrets:
        - name: regcred
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: web
          image: docker.io/champoi/champcaptures:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true