name: CDN Sync (assets/images → GCS)

on:
  push:
    branches: [ "main" ]
    paths:
      - "assets/images/**"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
  GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
  GCS_BUCKET: champoi-assets
  DEST_PREFIX: images          # ends up at gs://champoi-assets/images/...

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Auth to GCP (pick ONE of the two blocks below) ---

      # (A) Workload Identity Federation (recommended)
      - name: Debug WIF env
        run: |
          if [[ -n "${GCP_WIF_PROVIDER}" && -n "${GCP_SA_EMAIL}" ]]; then
            echo "WIF env vars are set."
          else
            echo "WIF env vars are NOT set. GCP_WIF_PROVIDER='${GCP_WIF_PROVIDER}' GCP_SA_EMAIL='${GCP_SA_EMAIL}'"
          fi

      - name: Auth with WIF
        if: ${{ env.GCP_WIF_PROVIDER != '' && env.GCP_SA_EMAIL != '' }}
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      # (B) Service Account JSON (fallback)
      - name: Auth with SA key (fallback)
        if: ${{ env.GCP_WIF_PROVIDER == '' || env.GCP_SA_EMAIL == '' }}
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud (gsutil)
        uses: google-github-actions/setup-gcloud@v2

      - name: Show gcloud info
        run: |
          gcloud --version
          gsutil --version
          gsutil ls -p "$(gcloud config get-value project -q || true)" || true

      # Mirror local assets/images → gs://champoi-assets/images
      # Toggle -d if you want deletions in bucket to match git (dangerous if you share the bucket).
      - name: rsync images to GCS
        run: |
          set -euo pipefail
          LOCAL_DIR="assets/images"
          GCS_URI="gs://${GCS_BUCKET}/${DEST_PREFIX}"
          if [ -d "${LOCAL_DIR}" ]; then
            gsutil -m rsync -r "${LOCAL_DIR}" "${GCS_URI}"
          else
            echo "No ${LOCAL_DIR} directory; skipping sync."
          fi

      # Apply long, immutable caching to all objects under /images
      - name: Set cache headers (immutable, 1 year)
        run: |
          set -euo pipefail
          GCS_URI="gs://${GCS_BUCKET}/${DEST_PREFIX}"

          IMAGE_EXTENSIONS="jpg jpeg png webp avif gif svg"
          IMAGE_PATTERNS=()

          for ext in $IMAGE_EXTENSIONS; do
            IMAGE_PATTERNS+=("${GCS_URI}/**/*.${ext}")
          done

          gsutil -m setmeta \
            -h "Cache-Control:public, max-age=31536000, immutable" \
            "${IMAGE_PATTERNS[@]}" || true

      # Optional: short cache for JSON/webmanifest (if you add any later)
      - name: Set short cache for JSON/manifest (optional)
        run: |
          set -euo pipefail
          GCS_URI="gs://${GCS_BUCKET}/${DEST_PREFIX}"
          gsutil -m setmeta \
            -h "Cache-Control:public, max-age=300" \
            "${GCS_URI}/**/*.json" "${GCS_URI}/**/*.webmanifest" || true