name: Security (Snyk)

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - ".github/**"
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: true

env:
  # Optional: set to your platform repo in org/name format (e.g., champoi/platform)
  PLATFORM_REPO: ""

permissions:
  contents: read
  security-events: write   # for SARIF upload
  pull-requests: write     # allows PR annotations

jobs:
  sca_iac_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout platform repo (optional)
        if: ${{ env.PLATFORM_REPO != '' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.PLATFORM_REPO }}
          path: _platform
          token: ${{ secrets.GH_CI_TOKEN }}

      - name: Setup Node for Snyk CLI (optional, but common)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Snyk CLI
        uses: snyk/actions/setup@0.4.0

      # --- SCA (Open Source) ---
      # For npm projects, Snyk can auto-detect manifest; if you need dev deps, add --dev
      - name: Snyk Open Source (SCA)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          # Scan only the Node/NPM project to produce a single SARIF run
          snyk test --severity-threshold=high --package-manager=npm --sarif-file-output=sca.sarif

      # --- IaC (Terraform, K8s, Helm) ---
      - name: Snyk IaC (platform repo)
        if: ${{ env.PLATFORM_REPO != '' }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk iac test _platform --severity-threshold=high --sarif-file-output=iac.sarif

      # --- SAST (Snyk Code) optional ---
      - name: Snyk Code (SAST) - optional
        if: ${{ false }}  # flip to true if you enable Snyk Code in org
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk code test --severity-threshold=high --sarif-file-output=code.sarif

      # Upload SARIF (SCA + IaC + Code if enabled)
      - name: Upload SARIF - SCA
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sca.sarif
          category: snyk-sca

      - name: Upload SARIF - IaC
        if: ${{ env.PLATFORM_REPO != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: iac.sarif
          category: snyk-iac

      - name: Upload SARIF - Code
        if: ${{ false }}  # flip to true if you enabled Snyk Code
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: code.sarif
          category: snyk-code
